{% set name = "swagger-ui-bundle" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/spec-first/swagger_ui_bundle/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9bedc35baaffa8d902da4224621f053edf730ca8b8bb8414d3a7f3650fe3a255

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - jinja2 >=3.0.0
    - python >=3.9,<4.0
    - poetry-core >=1.2.0
    - pip
  run:
    - jinja2 >=3.0.0
    - python >=3.9,<4.0

test:
  imports:
    - swagger_ui_bundle

about:
  home: https://github.com/spec-first/swagger_ui_bundle
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: swagger_ui_bundle - Swagger UI bundled for usage with Python
  dev_url: https://github.com/spec-first/swagger_ui_bundle

extra:
  recipe-maintainers:
    - kordian2k
    - msarahan
