{% set name = "swagger-ui-bundle" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/dtkav/swagger_ui_bundle/archive/{{ version }}.tar.gz"
  sha256: "9bedc35baaffa8d902da4224621f053edf730ca8b8bb8414d3a7f3650fe3a255"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - jinja2 >=2.0
    - pip
    - python
    - flake8
    - pytest-runner
  run:
    - jinja2 >=2.0
    - python

test:
  imports:
    - swagger_ui_bundle

about:
  home: "https://github.com/dtkav/swagger_ui_bundle"
  license: "Apache Version 2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "swagger_ui_bundle - swagger-ui files in a pip package"

extra:
  recipe-maintainers:
    - msarahan
